import type { SceneObject } from "../types";

/*
 * Villa Jaipur — Ground Floor, open-plan living space.
 * Room interior: x ∈ [-6, 6], z ∈ [-4, 4], wall height 3.2m.
 * Front edge (z = +4) is left open — dollhouse cutaway for viewing.
 */
export function createInitialObjects(): Record<string, SceneObject> {
  const list: SceneObject[] = [
    // ---------- FLOORS ----------
    {
      id: "floor-main",
      name: "Living Area Flooring",
      category: "floors",
      position: [0, -0.09, 0],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "stone-marble",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [12.6, 0.18, 8.6] } }],
    },
    {
      id: "floor-terrace",
      name: "Terrace Deck",
      category: "floors",
      position: [7.6, -0.075, -2],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "wood-teak",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [3.0, 0.15, 4.2] }, offset: [0, 0, 0] },
        { geo: { kind: "box", size: [3.0, 0.15, 1.6] }, offset: [0, -0.02, -3.0] },
      ],
    },

    // ---------- ARCHITECTURE / WALLS ----------
    {
      id: "wall-back-left",
      name: "Back Wall · Left",
      category: "walls",
      position: [-3.8, 1.6, -4.125],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [4.4, 3.2, 0.25] } }],
    },
    {
      id: "wall-back-right",
      name: "Back Wall · Right",
      category: "walls",
      position: [5.25, 1.6, -4.125],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [1.7, 3.2, 0.25] } }],
    },
    {
      id: "wall-back-header",
      name: "Glazing Header",
      category: "walls",
      position: [1.4, 2.9, -4.125],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: false,
      receiveShadow: false,
      parts: [{ geo: { kind: "box", size: [6.5, 0.6, 0.25] } }],
    },
    {
      id: "wall-left",
      name: "West Wall",
      category: "walls",
      position: [-6.1, 1.6, 0],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-beige",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [0.25, 3.2, 8.2] } }],
    },
    {
      id: "wall-right-a",
      name: "East Wall · North",
      category: "walls",
      position: [6.1, 1.6, -1.45],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [0.25, 3.2, 5.3] } }],
    },
    {
      id: "wall-right-b",
      name: "East Wall · South",
      category: "walls",
      position: [6.1, 1.6, 3.45],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: true,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [0.25, 3.2, 1.3] } }],
    },
    {
      id: "wall-right-header",
      name: "Door Header",
      category: "walls",
      position: [6.1, 2.7, 2.0],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-white",
      castShadow: false,
      receiveShadow: true,
      parts: [{ geo: { kind: "box", size: [0.25, 1.0, 1.6] } }],
    },

    // ---------- WINDOWS ----------
    {
      id: "window-glazing",
      name: "Full-Height Glazing",
      category: "windows",
      position: [1.4, 1.3, -4.125],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "glass-clear",
      castShadow: false,
      receiveShadow: false,
      parts: [
        { geo: { kind: "box", size: [5.9, 2.52, 0.04] }, offset: [0, 0, 0] },
        { geo: { kind: "box", size: [6.15, 0.09, 0.1] }, offset: [0, -1.26, 0], materialId: "metal-black" },
        { geo: { kind: "box", size: [6.15, 0.09, 0.1] }, offset: [0, 1.28, 0], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.07, 2.6, 0.07] }, offset: [-2.98, 0, 0], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.07, 2.6, 0.07] }, offset: [0, 0, 0], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.07, 2.6, 0.07] }, offset: [2.98, 0, 0], materialId: "metal-black" },
      ],
    },

    // ---------- DOORS ----------
    {
      id: "door-entry",
      name: "Entrance Door",
      category: "doors",
      position: [6.12, 1.1, 2.0],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "wood-teak",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [0.07, 2.16, 1.44] }, offset: [0, 0, 0] },
        { geo: { kind: "cylinder", radius: 0.025, height: 0.5 }, offset: [-0.08, 0.1, 0.5], materialId: "metal-brass" },
      ],
    },

    // ---------- COLUMNS ----------
    {
      id: "col-1",
      name: "Column 01",
      category: "columns",
      position: [-1.6, 1.6, -4.05],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "concrete-polished",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "cylinder", radius: 0.21, height: 3.2 } },
        { geo: { kind: "cylinder", radius: 0.27, height: 0.12 }, offset: [0, -1.54, 0] },
      ],
    },
    {
      id: "col-2",
      name: "Column 02",
      category: "columns",
      position: [4.4, 1.6, -4.05],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "concrete-polished",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "cylinder", radius: 0.21, height: 3.2 } },
        { geo: { kind: "cylinder", radius: 0.27, height: 0.12 }, offset: [0, -1.54, 0] },
      ],
    },

    // ---------- STAIRS ----------
    {
      id: "stairs-main",
      name: "Floating Staircase",
      category: "stairs",
      position: [-1.85, 0, -3.35],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "wood-oak",
      castShadow: true,
      receiveShadow: true,
      parts: Array.from({ length: 12 }, (_, i) => ({
        geo: { kind: "box" as const, size: [0.34, 0.13, 1.25] as [number, number, number] },
        offset: [-i * 0.36, 0.135 + i * 0.264, 0] as [number, number, number],
      })),
    },

    // ---------- CEILING (hidden by default — dollhouse view) ----------
    {
      id: "ceiling-main",
      name: "Ceiling Slab",
      category: "ceilings",
      position: [0, 3.32, 0],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: false,
      materialId: "paint-white",
      castShadow: false,
      receiveShadow: false,
      parts: [{ geo: { kind: "box", size: [12.6, 0.15, 8.6] } }],
    },

    // ---------- FURNITURE ----------
    {
      id: "sofa-lounge",
      name: "Lounge Sofa",
      category: "furniture",
      position: [-2.9, 0, 1.55],
      rotationY: Math.PI,
      scale: [1, 1, 1],
      visible: true,
      materialId: "fabric-linen",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [2.7, 0.38, 0.95] }, offset: [0, 0.19, 0] },
        { geo: { kind: "box", size: [2.7, 0.62, 0.24] }, offset: [0, 0.66, 0.36] },
        { geo: { kind: "box", size: [0.24, 0.56, 0.95] }, offset: [-1.23, 0.47, 0] },
        { geo: { kind: "box", size: [0.24, 0.56, 0.95] }, offset: [1.23, 0.47, 0] },
        { geo: { kind: "box", size: [0.82, 0.36, 0.92] }, offset: [0.94, 0.17, -0.9] },
        { geo: { kind: "box", size: [0.82, 0.58, 0.22] }, offset: [1.33, 0.63, -0.9] },
        { geo: { kind: "box", size: [0.42, 0.42, 0.14] }, offset: [-0.75, 0.58, 0.28], materialId: "fabric-velvet" },
        { geo: { kind: "box", size: [0.42, 0.42, 0.14] }, offset: [0.1, 0.58, 0.28], materialId: "fabric-cotton" },
        { geo: { kind: "box", size: [0.06, 0.12, 0.06] }, offset: [-1.1, 0.05, 0.32], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.06, 0.12, 0.06] }, offset: [1.1, 0.05, 0.32], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.06, 0.12, 0.06] }, offset: [-1.1, 0.05, -0.32], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.06, 0.12, 0.06] }, offset: [1.1, 0.05, -0.32], materialId: "metal-black" },
      ],
    },
    {
      id: "coffee-table",
      name: "Coffee Table",
      category: "furniture",
      position: [-1.7, 0, -0.55],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "wood-walnut",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [1.35, 0.06, 0.68] }, offset: [0, 0.34, 0] },
        { geo: { kind: "box", size: [0.05, 0.31, 0.05] }, offset: [-0.6, 0.155, 0.28], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.05, 0.31, 0.05] }, offset: [0.6, 0.155, 0.28], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.05, 0.31, 0.05] }, offset: [-0.6, 0.155, -0.28], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.05, 0.31, 0.05] }, offset: [0.6, 0.155, -0.28], materialId: "metal-black" },
        { geo: { kind: "sphere", radius: 0.07 }, offset: [0.35, 0.46, 0.1], color: "#dcd5c6", roughness: 0.4 },
      ],
    },
    {
      id: "chair-lounge",
      name: "Lounge Chair",
      category: "furniture",
      position: [-0.4, 0, 0.9],
      rotationY: Math.PI * 0.82,
      scale: [1, 1, 1],
      visible: true,
      materialId: "fabric-cotton",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [0.78, 0.16, 0.78] }, offset: [0, 0.32, 0] },
        { geo: { kind: "box", size: [0.78, 0.62, 0.18] }, offset: [0, 0.62, 0.32] },
        { geo: { kind: "box", size: [0.05, 0.3, 0.05] }, offset: [-0.32, 0.15, 0.3], materialId: "wood-walnut" },
        { geo: { kind: "box", size: [0.05, 0.3, 0.05] }, offset: [0.32, 0.15, 0.3], materialId: "wood-walnut" },
        { geo: { kind: "box", size: [0.05, 0.3, 0.05] }, offset: [-0.32, 0.15, -0.3], materialId: "wood-walnut" },
        { geo: { kind: "box", size: [0.05, 0.3, 0.05] }, offset: [0.32, 0.15, -0.3], materialId: "wood-walnut" },
      ],
    },
    {
      id: "console-tv",
      name: "Media Console",
      category: "furniture",
      position: [-2.6, 0, -3.55],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "wood-walnut",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [2.1, 0.42, 0.42] }, offset: [0, 0.36, 0] },
        { geo: { kind: "box", size: [2.0, 0.02, 0.02] }, offset: [0, 0.47, 0.2], materialId: "metal-brass" },
        { geo: { kind: "box", size: [0.05, 0.15, 0.35] }, offset: [-0.95, 0.07, 0], materialId: "metal-black" },
        { geo: { kind: "box", size: [0.05, 0.15, 0.35] }, offset: [0.95, 0.07, 0], materialId: "metal-black" },
      ],
    },
    {
      id: "side-table",
      name: "Side Table",
      category: "furniture",
      position: [-4.7, 0, 1.9],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "stone-marble",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "cylinder", radius: 0.32, height: 0.05 }, offset: [0, 0.48, 0] },
        { geo: { kind: "cylinder", radius: 0.05, height: 0.46 }, offset: [0, 0.23, 0], materialId: "metal-brass" },
        { geo: { kind: "cylinder", radius: 0.16, height: 0.03 }, offset: [0, 0.015, 0], materialId: "metal-brass" },
      ],
    },
    {
      id: "rug-main",
      name: "Area Rug",
      category: "decor",
      position: [-1.9, 0.005, 0.35],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "fabric-velvet",
      castShadow: false,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [3.6, 0.025, 2.5] }, offset: [0, 0, 0] },
        { geo: { kind: "box", size: [3.3, 0.028, 2.2] }, offset: [0, 0.002, 0], materialId: "fabric-cotton" },
      ],
    },

    // ---------- FIXTURES ----------
    {
      id: "pendant-main",
      name: "Pendant Light",
      category: "fixtures",
      position: [-1.7, 0, -0.55],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "metal-black",
      castShadow: false,
      receiveShadow: false,
      parts: [
        { geo: { kind: "cylinder", radius: 0.008, height: 0.9 }, offset: [0, 2.72, 0] },
        { geo: { kind: "cone", radius: 0.26, height: 0.3 }, offset: [0, 2.1, 0] },
        { geo: { kind: "sphere", radius: 0.07 }, offset: [0, 2.0, 0], color: "#ffd9a0", emissiveIntensity: 2.4 },
      ],
    },
    {
      id: "floor-lamp",
      name: "Arc Floor Lamp",
      category: "fixtures",
      position: [-4.9, 0, -1.6],
      rotationY: Math.PI * 0.15,
      scale: [1, 1, 1],
      visible: true,
      materialId: "metal-brass",
      castShadow: false,
      receiveShadow: false,
      parts: [
        { geo: { kind: "cylinder", radius: 0.16, height: 0.03 }, offset: [0, 0.015, 0] },
        { geo: { kind: "cylinder", radius: 0.02, height: 1.9 }, offset: [0, 0.95, 0] },
        { geo: { kind: "cone", radius: 0.18, height: 0.24 }, offset: [0.12, 1.95, 0] },
        { geo: { kind: "sphere", radius: 0.06 }, offset: [0.12, 1.86, 0], color: "#ffe2b0", emissiveIntensity: 2.2 },
      ],
    },

    // ---------- PLANTS ----------
    {
      id: "plant-large",
      name: "Fiddle Leaf Fig",
      category: "plants",
      position: [4.9, 0, -2.6],
      rotationY: 0.4,
      scale: [1, 1, 1],
      visible: true,
      materialId: "concrete-textured",
      castShadow: true,
      receiveShadow: false,
      parts: [
        { geo: { kind: "cylinder", radius: 0.24, height: 0.42 }, offset: [0, 0.21, 0] },
        { geo: { kind: "cylinder", radius: 0.03, height: 1.15 }, offset: [0, 0.95, 0], color: "#5a4632", roughness: 0.9 },
        { geo: { kind: "sphere", radius: 0.42 }, offset: [0.05, 1.75, 0], color: "#4a6b45", roughness: 0.85 },
        { geo: { kind: "sphere", radius: 0.3 }, offset: [-0.28, 1.45, 0.12], color: "#55764e", roughness: 0.85 },
        { geo: { kind: "sphere", radius: 0.26 }, offset: [0.3, 1.4, -0.15], color: "#40603c", roughness: 0.85 },
      ],
    },
    {
      id: "plant-pot",
      name: "Ceramic Pot",
      category: "plants",
      position: [-5.4, 0, -2.9],
      rotationY: 0,
      scale: [1, 1, 1],
      visible: true,
      materialId: "tile-ceramic",
      castShadow: true,
      receiveShadow: false,
      parts: [
        { geo: { kind: "cylinder", radius: 0.19, height: 0.34 }, offset: [0, 0.17, 0] },
        { geo: { kind: "sphere", radius: 0.26 }, offset: [0, 0.52, 0], color: "#5d7350", roughness: 0.88 },
      ],
    },

    // ---------- DECOR ----------
    {
      id: "art-panel",
      name: "Wall Art",
      category: "decor",
      position: [-5.93, 1.65, -0.6],
      rotationY: Math.PI / 2,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-charcoal",
      castShadow: false,
      receiveShadow: false,
      parts: [
        { geo: { kind: "box", size: [1.3, 0.9, 0.05] }, offset: [0, 0, 0] },
        { geo: { kind: "box", size: [1.34, 0.94, 0.02] }, offset: [0, 0, -0.028], materialId: "metal-brass" },
      ],
    },
    {
      id: "books-decor",
      name: "Book Stack",
      category: "decor",
      position: [0.6, 0, -3.4],
      rotationY: 0.3,
      scale: [1, 1, 1],
      visible: true,
      materialId: "paint-charcoal",
      castShadow: true,
      receiveShadow: true,
      parts: [
        { geo: { kind: "box", size: [0.26, 0.035, 0.19] }, offset: [0, 0.017, 0] },
        { geo: { kind: "box", size: [0.23, 0.03, 0.17] }, offset: [0.015, 0.05, 0.01], materialId: "stone-travertine" },
        { geo: { kind: "box", size: [0.2, 0.03, 0.15] }, offset: [-0.01, 0.082, 0], materialId: "fabric-velvet" },
      ],
    },
  ];

  return Object.fromEntries(list.map((o) => [o.id, o]));
}

export interface HierarchyNode {
  label: string;
  objectIds?: string[];
  children?: HierarchyNode[];
}

export const SCENE_HIERARCHY: HierarchyNode = {
  label: "PROJECT",
  children: [
    {
      label: "Villa Jaipur",
      children: [
        { label: "Floors", objectIds: ["floor-main", "floor-terrace"] },
        {
          label: "Architecture",
          children: [
            { label: "Walls", objectIds: ["wall-back-left", "wall-back-right", "wall-back-header", "wall-left", "wall-right-a", "wall-right-b", "wall-right-header"] },
            { label: "Ceilings", objectIds: ["ceiling-main"] },
            { label: "Doors", objectIds: ["door-entry"] },
            { label: "Windows", objectIds: ["window-glazing"] },
            { label: "Stairs", objectIds: ["stairs-main"] },
            { label: "Columns", objectIds: ["col-1", "col-2"] },
          ],
        },
        {
          label: "Interior",
          children: [
            { label: "Furniture", objectIds: ["sofa-lounge", "coffee-table", "chair-lounge", "console-tv", "side-table"] },
            { label: "Fixtures", objectIds: ["pendant-main", "floor-lamp"] },
            { label: "Plants", objectIds: ["plant-large", "plant-pot"] },
            { label: "Decor", objectIds: ["rug-main", "art-panel", "books-decor"] },
          ],
        },
        {
          label: "Lighting",
          objectIds: [],
          children: [],
        },
      ],
    },
  ],
};
